### ISSUE TITLE
Loom model checking

### ISSUE THREAD

**Issue by loyd** [wvwwvwwv/scalable-delayed-dealloc#1]
[The original issue](https://github.com/wvwwvwwv/scalable-concurrent-containers/issues/133)

**Comment by changgyoopark-db** [comment]
Added a real loom test - more to be added later.

**Comment by loyd** [comment]
It's very cool. I mocked `AtomicShared`: https://github.com/loyd/idr-ebr/blob/238098efb4e480f690e40822f76ab8a66377c304/src/loom.rs#L34-L44 to run under the loom.

Can you use the dedicated `cfg(sdd_loom)` instead (or in addition to) `cfg(loom)` to allow enabled/disabled in dependent optionally?

**Comment by loyd** [comment]
Oh, I see, `AtomicShared` doesn't use `loom::AtomicPtr`, so it's not completed yet. Anyway, thanks for the initiative

**Comment by loyd** [comment]
Note also that it will most likely require `loom` as the dependency instead of dev-dependency, which can lead to preserving users' `Cargo.lock` files. It can be fixed in the same way as https://github.com/crossbeam-rs/crossbeam/pull/666

**Comment by wvwwvwwv** [comment]
@loyd Thanks for the ideas. I’ll reopen this as the current set of tests is far from complete.

**Comment by wvwwvwwv** [comment]
I found the way `crossbeam_epoch` did to support loom testing a bit dirty, so I just added the `loom` feature (cfg(feature = "loom")) without relying on an extra `cfg` parameter. it will still be possible to conditionally activate `loom` types only during a test by using `cfg(test)`, but I never tested this -> if it is not possible, please let me know, then I'll add an additional `cfg` gate.

-> SDD 1.7.0
